### ISSUE TITLE
Relaxation of leidenalg==0.7.0 requirement?

### ISSUE THREAD

**Issue by ajitjohnson** [ShobiStassen/PARC#14]
Hi @ShobiStassen 

I see that you have leidenalg==0.7.0 as a requirement. Is there any particular reason why it needs to be that exact version? For people like me who use version managers, that specific requirement makes it difficult to use `parc`. Is it possible to change it to something like `leidenalg>=0.7.0` if the version is not critical? Thank you.

```
install_requires=['pybind11','numpy','scipy','pandas','hnswlib','python-igraph','leidenalg==0.7.0','umap-learn']
```

Best,
Ajit.

**Comment by ShobiStassen** [comment]
hi @ajitjohnson 

thanks for your message - about half a year ago some changes were made to leidenalg that made it (unexpectedly) slower for very large datasets. The Leidenalg authors have now corrected for this, but there is still a minor slow down compared to version0.7.0 on extremely large datasets (millions of cells)  but i think you should be fine to use PARC on the corrected leidenalg versions. 
I have relaxed the requirement now, let me know if that works for you then
Shobi

**Comment by ajitjohnson** [comment]
Thanks a lot, @ShobiStassen. Yeah, I saw your convo with Traag. Thank you so much for bringing this issue forward and fixing it.
