### ISSUE TITLE
Hello! I am getting AttributeError, when trying to import parc 

### ISSUE THREAD

**Issue by quantumkisa** [ShobiStassen/PARC#19]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_2109246/3403208955.py in <module>
----> 1 import parc

~/user_venv/lib/python3.7/site-packages/parc/__init__.py in <module>
----> 1 from ._parc import PARC

~/user_venv/lib/python3.7/site-packages/parc/_parc.py in <module>
      6 from scipy.sparse import csr_matrix
      7 import igraph as ig
----> 8 import leidenalg
      9 import time
     10 import umap

~/user_venv/lib/python3.7/site-packages/leidenalg/__init__.py in <module>
     33 not immediately available in :func:`leidenalg.find_partition`.
     34 """
---> 35 from .functions import ALL_COMMS
     36 from .functions import ALL_NEIGH_COMMS
     37 from .functions import RAND_COMM

~/user_venv/lib/python3.7/site-packages/leidenalg/functions.py in <module>
     21     return graph.__graph_as_cobject()
     22 
---> 23 from .VertexPartition import *
     24 from .Optimiser import *
     25 

~/user_venv/lib/python3.7/site-packages/leidenalg/VertexPartition.py in <module>
      6 PY3 = (sys.version > '3')
      7 
----> 8 class MutableVertexPartition(_ig.VertexClustering):
      9   """ Contains a partition of graph, derives from :class:`ig.VertexClustering`.
     10 

AttributeError: module 'igraph' has no attribute 'VertexClustering'

**Comment by ShobiStassen** [comment]
Hi, 
Sorry for the late reply, I am actually out of office next week but some suggestions for troubleshooting, do you have both igraph and python-igraph in your environment?
It might help to uninstall python-igraph and igraph in case you had an old version of python-igraph that is not compatible with leidenalg.
After that you can pip install igraph and perhaps first just check if you can import leidenlag, and then see if import parc works.

I'll try to get you a more comprehensive answer next week but I think there is some version issue related to igraph.

**Comment by ShobiStassen** [comment]
@quantumkisa hi,
I just tried installing parc in a clean environment and running the sample code in the Readme. I dont get any issues, so let me know if you managed to install parc
