### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by SansMorel** [ShobiStassen/PARC#8]
Hi, 

This is not an issue, I just wanted to give you my thanks. This work is awesome!

**Comment by ShobiStassen** [comment]
Hej og mange tak! I hope it's useful for your work! do let me know if you run into any issues and I'll be happy to help

**Comment by chenxofhit** [comment]
@SansMorel how do you think of this method, I am always focusing on the clustering method on a large dataset, besides the DL method.

**Comment by SansMorel** [comment]
@chenxofhit I have large CyTOF datasets that I cluster. I have tried several other methods, such as k-means, phenograph, x-shift, leiden, FlowSOM, but they all have drawbacks (mainly being very slow or unable to capture subpopulations). For my data sets, graph based methods have proven most accurate, as they are able to capture subpopulations, but then you get into the issue of overfragmentation when choosing the correct k and they also tend to be slow very slow. Parc, however, has been able to make a very good compromise in this area.

**Comment by chenxofhit** [comment]
@SansMorel Thanks for your sharing your experience with this method. The method it really takes advantage of the first step, which is really tricky at the first glance. Thanks for @ShobiStassen contributing this excellent method.

**Comment by ShobiStassen** [comment]
hi, thanks for your very kind messages. Please let me know if you need any pointers on tuning the params.
cheers

**Comment by ajitjohnson** [comment]
Brilliant work. One of the smoothest new methods that worked in the first try. Well done @ShobiStassen If I were you, I will talk with Alex to get it integrated into Scanpy for more visibility and generally for the benefit of the community. All the best.
