### ISSUE TITLE
Controlling the number of clusters

### ISSUE THREAD

**Issue by ajitjohnson** [ShobiStassen/PARC#9]
In Leiden clustering, we could pass a resolution parameter value to control the coarseness of the clustering. Is it possible to expose that parameter?

**Comment by ShobiStassen** [comment]
Hi Ajit, sure we can expose the resolution parameter. That's a good idea. Will try to do it today and let you know when it's done !
In case you are trying to uncover some small populations, the level of graph pruning is quite impactful. (The supplementary materials of our paper has more details on this)
Shobi

**Comment by ajitjohnson** [comment]
Thank you @ShobiStassen I am interested in the contrary actually- to reduce the number of total clusters.

**Comment by ShobiStassen** [comment]
hi, i just added the resolution_parameter, do let me know if it works for you. If you are trying to reduce the number of clusters, perhaps also try to set both pruning parameters to a value of 1 or 2 (which minimizes the extent of pruning). You can also increase K (NN), the method is still very fast.

**Comment by ajitjohnson** [comment]
Thank you for your super quick implementation. Works perfectly. Thank you.
